OFICIOS = {
    "General": {
        "iva": 21.0,
        "extras": [],
        "conceptos": [],
        "notas": "Validez del presupuesto: 30 días. Pago: 50% al aceptar y 50% a la entrega.",
    },
    "Reformas y albañilería": {
        "iva": 10.0,
        "extras": ["Dirección de la obra", "Plazo de ejecución"],
        "conceptos": [
            ("Demolición de tabiques y escombros", "m2", 25.0),
            ("Alicatado de paredes", "m2", 35.0),
            ("Solado con cerámica o porcelánico", "m2", 40.0),
            ("Tabique de ladrillo o pladur", "m2", 30.0),
            ("Enfoscado y guarnecido de paredes", "m2", 18.0),
            ("Reforma de baño completo", "ud", 3500.0),
            ("Contenedor de escombros", "ud", 180.0),
            ("Mano de obra oficial", "h", 25.0),
        ],
        "notas": "Validez: 30 días. Pago: 30% al aceptar, 40% a mitad de obra y 30% al terminar. Los trabajos no incluidos se presupuestan aparte.",
    },
    "Fontanería": {
        "iva": 21.0,
        "extras": ["Dirección de la instalación"],
        "conceptos": [
            ("Visita y diagnóstico", "visita", 40.0),
            ("Reparación de fuga", "ud", 90.0),
            ("Cambio de grifo", "ud", 70.0),
            ("Instalación de inodoro", "ud", 150.0),
            ("Instalación de termo eléctrico", "ud", 220.0),
            ("Desatasco de tubería", "ud", 100.0),
            ("Punto de agua nuevo", "punto", 60.0),
            ("Mano de obra", "h", 35.0),
        ],
        "notas": "Validez: 15 días. Pago al terminar el trabajo. Materiales no incluidos salvo que se indique.",
    },
    "Electricidad": {
        "iva": 21.0,
        "extras": ["Dirección de la instalación", "Potencia contratada"],
        "conceptos": [
            ("Visita y revisión de instalación", "visita", 40.0),
            ("Punto de luz", "punto", 45.0),
            ("Enchufe o toma de corriente", "punto", 40.0),
            ("Cuadro eléctrico nuevo", "ud", 350.0),
            ("Cambio de magnetotérmico o diferencial", "ud", 60.0),
            ("Instalación de luminaria", "ud", 35.0),
            ("Línea de cable", "ml", 12.0),
            ("Mano de obra", "h", 35.0),
        ],
        "notas": "Validez: 30 días. Pago: 50% al aceptar y 50% al terminar. Boletín y legalización no incluidos salvo que se indique.",
    },
    "Pintura": {
        "iva": 10.0,
        "extras": ["Dirección de la obra", "Superficie aproximada m2"],
        "conceptos": [
            ("Pintura plástica en paredes", "m2", 6.0),
            ("Pintura de techos", "m2", 7.0),
            ("Lacado de puertas", "ud", 70.0),
            ("Lacado de ventanas", "ud", 60.0),
            ("Alisado de paredes", "m2", 12.0),
            ("Reparación de grietas y desperfectos", "m2", 8.0),
            ("Protección de muebles y suelos", "servicio", 60.0),
            ("Mano de obra", "h", 22.0),
        ],
        "notas": "Validez: 30 días. Pago: 50% al empezar y 50% al terminar. Incluye pintura y material de protección.",
    },
    "Carpintería y ebanistería": {
        "iva": 21.0,
        "extras": ["Dirección de entrega", "Plazo de entrega"],
        "conceptos": [
            ("Puerta interior a medida", "ud", 280.0),
            ("Armario empotrado a medida", "ml", 450.0),
            ("Mueble de cocina a medida", "ml", 400.0),
            ("Reparación de mueble", "ud", 60.0),
            ("Instalación de suelo laminado", "m2", 18.0),
            ("Rodapié", "ml", 6.0),
            ("Barnizado o lasurado", "m2", 20.0),
            ("Mano de obra", "h", 28.0),
        ],
        "notas": "Validez: 30 días. Pago: 50% al encargar y 50% a la entrega. Medidas definitivas tras visita al local.",
    },
    "Climatización y aire acondicionado": {
        "iva": 21.0,
        "extras": ["Dirección de la instalación", "Equipo y marca"],
        "conceptos": [
            ("Instalación de aire acondicionado split", "ud", 450.0),
            ("Instalación de conductos", "ml", 60.0),
            ("Carga de gas refrigerante", "ud", 90.0),
            ("Mantenimiento y limpieza de equipo", "ud", 70.0),
            ("Reparación de avería", "visita", 60.0),
            ("Soporte exterior y bancada", "ud", 50.0),
            ("Desmontaje de equipo antiguo", "ud", 80.0),
            ("Mano de obra", "h", 35.0),
        ],
        "notas": "Validez: 30 días. Pago: 50% al aceptar y 50% al terminar. El equipo se factura aparte si no se indica lo contrario.",
    },
    "Cerrajería": {
        "iva": 21.0,
        "extras": ["Dirección del servicio"],
        "conceptos": [
            ("Apertura de puerta sin llave", "servicio", 70.0),
            ("Cambio de cerradura", "ud", 90.0),
            ("Instalación de cerradura de seguridad", "ud", 150.0),
            ("Copia de llaves", "ud", 3.0),
            ("Instalación de puerta blindada", "ud", 250.0),
            ("Reparación de persiana o reja", "ud", 70.0),
            ("Desplazamiento", "servicio", 25.0),
            ("Mano de obra", "h", 30.0),
        ],
        "notas": "Validez: 15 días. Pago al terminar el servicio.",
    },
    "Jardinería": {
        "iva": 21.0,
        "extras": ["Dirección del jardín", "Superficie aproximada m2"],
        "conceptos": [
            ("Mantenimiento mensual de jardín", "servicio", 120.0),
            ("Poda de árboles", "ud", 60.0),
            ("Corte de césped", "m2", 0.5),
            ("Plantación de arbustos", "ud", 20.0),
            ("Instalación de riego automático", "m2", 6.0),
            ("Retirada de restos vegetales", "servicio", 50.0),
            ("Tratamiento fitosanitario", "servicio", 60.0),
            ("Mano de obra", "h", 20.0),
        ],
        "notas": "Validez: 30 días. Pago al terminar cada servicio. Plantas y material según lo acordado.",
    },
    "Taller mecánico": {
        "iva": 21.0,
        "extras": ["Vehículo marca y modelo", "Matrícula", "Kilómetros"],
        "conceptos": [
            ("Revisión general", "ud", 60.0),
            ("Cambio de aceite y filtro", "ud", 70.0),
            ("Cambio de pastillas de freno", "ud", 90.0),
            ("Cambio de neumáticos", "ud", 70.0),
            ("Diagnosis electrónica", "ud", 40.0),
            ("Cambio de batería", "ud", 110.0),
            ("Cambio de correa de distribución", "ud", 350.0),
            ("Mano de obra", "h", 40.0),
        ],
        "notas": "Validez: 15 días. Cualquier reparación adicional se consultará antes de realizarla. Pago al recoger el vehículo.",
    },
    "Limpieza profesional": {
        "iva": 21.0,
        "extras": ["Dirección del servicio", "Frecuencia"],
        "conceptos": [
            ("Limpieza general de vivienda", "h", 15.0),
            ("Limpieza de oficina", "m2", 1.2),
            ("Limpieza de cristales", "m2", 2.0),
            ("Limpieza de fin de obra", "m2", 4.0),
            ("Limpieza de comunidad", "servicio", 150.0),
            ("Desinfección", "servicio", 80.0),
            ("Abrillantado de suelos", "m2", 5.0),
            ("Productos y material", "servicio", 25.0),
        ],
        "notas": "Validez: 30 días. Pago mensual por adelantado en servicios periódicos y al terminar en servicios puntuales.",
    },
}
